[database]
insert_subscribers = '''
INSERT INTO subscribers (subscriber_id, channel_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
'''

insert_streamers = '''
WITH to_insert AS (
   INSERT INTO streamers AS entries (username, service, service_id)
   VALUES ($1, $2, $3)
   ON CONFLICT DO NOTHING
   RETURNING entries.streamer_id
)
SELECT streamer_id FROM to_insert
UNION ALL
SELECT streamer_id FROM streamers WHERE username = $1 AND service = $2
LIMIT 1;
'''

insert_subscriptions = '''
INSERT INTO subscriptions (subscriber_id, streamer_id)
VALUES ($1, $2)
'''

del_subscription = '''
DELETE FROM subscriptions
WHERE streamer_id IN (
      SELECT streamer_id
        FROM streamers
       WHERE service = $1
         AND username = $2
)
AND subscriber_id = $3
'''

get_all_streamers_from_service = '''
SELECT *
  FROM streamers
 WHERE service = $1
'''

get_all_subscribers = '''
SELECT *
  FROM subscribers
'''

delete_subscriber = '''
DELETE FROM subscribers
WHERE subscriber_id = $1
'''

get_subscribers_from_streamer = '''
SELECT channel_id
  FROM subscribers
       INNER JOIN subscriptions
       USING (subscriber_id)
       INNER JOIN streamers
       USING (streamer_id)
 WHERE streamer_id = $1
'''

get_subscriptions_from_subscriber = '''
SELECT username
  FROM subscriptions
       INNER JOIN subscribers
       USING (subscriber_id)
       INNER JOIN streamers
       USING (streamer_id)
 WHERE subscriber_id = $1
   AND service = $2
ORDER BY username
'''

[help_strings]
add_command_help = """
Subscribing to streamers:
    snb?{service} add username
    Example: snb?{service} add mykegreywolf

Subscribing a channel to streamers:
    snb?{service} add username channel
    Example: snb?{service} add mykegreywolf #general
"""

del_command_help = """
Unsubscribing to streamers:
    snb?{service} del username
    Example: snb?{service} del mykegreywolf

Unsubscribing a channel to streamers:
    snb?{service} del username channel
    Example: snb?{service} del mykegreywolf #general
"""

list_command_help = """
Listing your streamers:
    snb?{service} list
    Example: snb?{service} list

Listing a channel's streamers:
    snb?{service} list channel
    Example: snb?{service} list #general
"""

